### ISSUE TITLE
Fix to allow spy() with implementations (not interfaces) - IllegalStateException: Injecting null 

### ISSUE THREAD

**Issue by rbygrave** [dinject/dinject#25]
Where `Grinder` is an implementation class and not an interface
```java
  @Test
  public void withMockitoSpy_postLoadSetup_expect_spyUsed() {

    try (BeanContext context = new BootContext()
      .withSpy(Pump.class)
      .withSpy(Grinder.class) // HERE
      .load()) {

      ...

      CoffeeMaker coffeeMaker = context.getBean(CoffeeMaker.class);
      coffeeMaker.makeIt();

      ...

      Grinder grinder = context.getBean(Grinder.class);
      verify(grinder).grindBeans(); // throws IllegalStateException
    }
  }
```

```
java.lang.IllegalStateException: Injecting null for org.example.coffee.grind.Grinder when creating class org.example.coffee.CoffeeMaker - potential beans to inject: []

	at io.dinject.core.DBuilder.get(DBuilder.java:223)
	at io.dinject.core.DBuilder.get(DBuilder.java:207)
	at org.example.coffee.CoffeeMaker$di.build(CoffeeMaker$di.java:14)
	at org.example.coffee._di$Factory.build_CoffeeMaker(_di$Factory.java:228)
	at org.example.coffee._di$Factory.createContext(_di$Factory.java:92)
	at io.dinject.BootContext.load(BootContext.java:364)
	at org.example.coffee.BootContext_mockitoSpyTest.withMockitoSpy_postLoadSetup_expect_spyUsed(BootContext_mockitoSpyTest.java:64)
	...
```

**Comment by yaskor** [comment]
Tested with 1.7-Snapshot. Still failing with "NotAMock"

**Comment by rbygrave** [comment]
Are you able to produce a test case?

**Comment by yaskor** [comment]
I will try my best :-)
